name: Docker

on:
  schedule:
    - cron: '15 0 * * 5'
  push:
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  branch: master
  platforms_to_build_for: linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.platforms_to_build_for }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
